title: Zichen Ma
#logo: "/images/sobi.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D Candidate 
  <br>
  Department of Statistics
  <br>
  University of South Carolina
  <br>
  Email: zichen@email.sc.edu
  <br><br>
  <a href="https://www.linkedin.com/in/zichen-ma-69aba668/">LinkedIn</a> 
  <br><br>
  <a href="ZichenMa-USC.github.io/teaching">Teaching</a>
  <br><br>
  <a href="ZichenMa-USC.github.io/research">Research</a>
  <br><br> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
