title: Tahmidul Islam
#logo: "/images/sobi.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D Candidate 
  Department of Statistics, University of South Carolina 
  <br><br>
  <a href="https://linkedin.com/in/tahmidul">LinkedIn</a> 
  <br><br>
  <a href="tahmid-usc.github.io/teaching">Teaching</a>
  <br><br>
  <a href="tahmid-usc.github.io/research">Research</a>
  <br><br> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
