title: Tahmidul Islam
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D Candidate 
  <br><br>
  Department of Statistics, University of South Carolina 
  <br><br>
  <a href="https://linkedin.com/in/tahmidul">View My LinkedIn Profile</a> 
  <br><br>
  <h3><a href="tahmid-usc.github.io/teaching">Teaching</a></h3>
  <br><br>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
